name: Publish Website to GitHub Pages
on:
  push:
      
  # Manual trigger
  workflow_dispatch:

  # External trigger
  repository_dispatch:
    types: 
      - docs-deploy

# Allow one concurrent deployment for the workflow
concurrency:
  group: page-deploy
  cancel-in-progress: true

jobs:
  build:
    permissions:
        contents: read
        pages: write
        id-token: write
    if: github.repository_owner == 'Synodic-Software'
    uses: synodic-software/.github/.github/workflows/website-publish-pages.yml@stable